# Generated by Django 3.1.2 on 2022-04-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0004_auto_20220413_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Rent Price Per Month')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Rent Time')),
                ('start_at', models.DateField(verbose_name='Start Date')),
                ('months', models.IntegerField(default=1, verbose_name='Rent Months')),
                ('end_at', models.DateField(verbose_name='End Date')),
                ('money', models.FloatField(default=0, verbose_name='total money')),
                ('status', models.CharField(choices=[('normal', 'normal'), ('apply to unsubscribe', 'apply to unsubscribe'), ('unsubscribed', 'unsubscribed'), ('delayed', 'delayed')], default='normal', max_length=32, verbose_name='status')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_rent_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Rents',
                'verbose_name_plural': 'User Rents',
                'ordering': ('-create_at',),
            },
        ),
    ]
