# Generated by Django 3.1.2 on 2022-04-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20220413_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='rent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.rent', verbose_name='from'),
        ),
    ]
