# Generated by Django 3.1.2 on 2022-04-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20220413_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsubscribe',
            old_name='update_time',
            new_name='update_at',
        ),
    ]
