# Generated by Django 3.1.2 on 2022-04-13 19:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('picture', models.ImageField(upload_to='houses')),
                ('house_type', models.CharField(choices=[('Houses', 'Houses'), ('Flats/Apartments', 'Flats/Apartments'), ('House/Flat Share', 'House/Flat Share'), ('Student Private Halls', 'Student Private Halls'), ('Other', 'Other')], max_length=32, verbose_name='house type')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='detail')),
                ('area', models.FloatField(verbose_name='area')),
                ('price', models.FloatField(verbose_name='price(permonth)')),
                ('position', models.CharField(max_length=64, verbose_name='position')),
                ('bed_num', models.IntegerField(default=1, verbose_name='bed num')),
                ('post_code', models.CharField(default='430071', max_length=32, verbose_name='post code')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='online time')),
                ('status', models.CharField(choices=[('wait to rent', 'wait to rent'), ('rented', 'rented')], default='wait to rent', max_length=32, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'house',
                'ordering': ('-create_at',),
            },
        ),
    ]
